### ISSUE TITLE
"eth_getEncryptionPublicKey" in android SDK

### ISSUE THREAD

**Issue by Rathore2696** [MetaMask/metamask-android-sdk#119] opened 2024-07-03 08:39 UTC
# Bug Report
  There is a method in MetaMask SDK that gets the encryptionpublic key using the "eth_getEncryptionPublicKey" method in the request

  How to use this in the Android application?
  Is this feature implemented but removed in the latest version of the MetaMask SDK for Android, if so which version should I have to use this method?
  Is there any alternative way to get the same result in the MetaMask SDK for Android?

**Comment by elefantel** [comment] 2024-07-09 08:20
Hi @Rathore2696 see the MetaMask documentation regarding that RPC method 
https://docs.metamask.io/wallet/reference/eth_getencryptionpublickey/

How do you wish to use the wallet's public key?

**Comment by Rathore2696** [comment] 2024-07-09 12:34
I am using MetaMask SDK v5.4 for Android in Android Studio - Koala

Below is the code I use to connect with the MetaMask(Wallet) mobile application in an Android smartphone from my Android application:
![image_2024_07_09T12_18_31_032Z](https://github.com/MetaMask/metamask-android-sdk/assets/174592947/d96cb505-3225-4d0e-886f-7ff58e508279)

And the MetaMask wallet gets connected to my application and in the callback I am storing the result that contains my wallet address in a variable of type LiveData<EthereumState> . When I try to get the public encryption key from my connected wallet in my Android application, it returns the result as follows:-
![image_2024_07_09T12_03_05_773Z](https://github.com/MetaMask/metamask-android-sdk/assets/174592947/cc7ede43-e35e-4320-9740-6d9c575d990d)

With the help of the JSON RPC API(https://docs.metamask.io/wallet/reference/eth_getencryptionpublickey/) I am able to get the encrypted public key but not via the SDK. How to get it in my mobile app?. Please suggest a way, thank you in advance.

**Comment by elefantel** [comment] 2024-07-10 12:05
Ok I see what the issue is. We did not include `eth_getEncryptionPublicKey` among the supported methods for working with the wallet because it is marked as deprecated in that MetaMask documentation I sent you. 

The way you can make it to work in the meantime would be to not provide the `SDKOptions` and then all traffic will default to the wallet. Currently that RPC call is going via Infura and Infura does not support it.

**Comment by Rathore2696** [comment] 2024-07-10 16:35
I tried as per your suggestion by removing the SDKOptions from the parameters passed in the Ethereum constructor to create the Ethereum instance, but still the same error message is received after calling the eth_getEncryptionPublicKey logic I am using in the Android Studio.

![Screenshot_1](https://github.com/MetaMask/metamask-android-sdk/assets/174592947/ff3c63cc-29fa-4b94-bcbc-c99753b063c6)

**Comment by elefantel** [comment] 2024-07-12 08:16
@Rathore2696 ok that means MetaMask no longer supports that method. As you can see in the documentation in the link above I shared the method is marked as deprecated, with a note: "This method is deprecated and may be removed in the future." I will close this ticket.

**Closed by elefantel** 2024-07-12 08:16 UTC
Labels: enhancement

**Comment by Rathore2696** [comment] 2024-07-12 12:40
I need to retrieve that encryption public key. If it is not supported in the MetaMask mobile SDK for android, then how do I get that key?
